### ISSUE TITLE
Two select open at the same time

### ISSUE THREAD

**Issue by volcanioo** [Blobfolio/blob-select#1]
Hi, i am using your plugin but i have problem.

<img width="590" alt="screen shot 2018-04-11 at 18 14 48" src="https://user-images.githubusercontent.com/14016028/38626093-8cf01fb4-3db4-11e8-83e7-e24c640083ca.png">

Anytime, if you want look this demo: https://www.cssscript.com/demo/select-box-replacement-blob-select/ (Click two select)

**Comment by joshstoik1** [comment]
Thanks @msdvcii,

I just pushed a potential fix in `2.0.2`. Would you mind giving that a shot to see if it fixes your problem?

**Comment by msdvcii** [comment]
Thanks @joshstoik1 for quickly answer.

My problem fixed. 🎉🎉🎉🎉

**Comment by volcanioo** [comment]
Thanks @joshstoik1 for quickly answer.

My problem fixed. Do you explain how I managed to fix?
http://twitter.com/mehmetsdvci
